name: GitHub-hosted runners
description: The list of GitHub-hosted runners
branding:
  icon: list
  color: green
outputs:
  all:
    description: All runners
    value: ${{ steps.all.outputs.json }}
  latest:
    description: Latest runners
    value: ${{ steps.latest.outputs.json }}
  ubuntu:
    description: Ubuntu runners
    value: ${{ steps.ubuntu.outputs.json }}
  windows:
    description: Windows runners
    value: ${{ steps.windows.outputs.json }}
  macos:
    description: macOS runners
    value: ${{ steps.macos.outputs.json }}
runs:
  using: composite
  steps:
    - id: list
      run: |
        json=$(curl -sS https://json.schemastore.org/github-workflow.json \
          | jq -c '.definitions.normalJob.properties["runs-on"].oneOf | map(select(.type == "string")) | first | .enum | map(select(. != "self-hosted"))')
        echo "json=${json}" >> $GITHUB_OUTPUT
    - id: all
      run: |
        json=$(echo ${list} | jq -c 'map(select(endswith("-latest") | not))'
        echo "json=${json}" >> $GITHUB_OUTPUT
      env:
        list: ${{ steps.list.outputs.json }}
    - id: latest
      run: |
        json=$(echo ${list} | jq -c 'map(select(endswith("-latest")))'
        echo "json=${json}" >> $GITHUB_OUTPUT
      env:
        list: ${{ steps.list.outputs.json }}
    - id: ubuntu
      run: |
        json=$(echo ${list} | jq -c 'map(select(startswith("ubuntu-")))'
        echo "json=${json}" >> $GITHUB_OUTPUT
      env:
        list: ${{ steps.list.outputs.json }}
    - id: windows
      run: |
        json=$(echo ${list} | jq -c 'map(select(startswith("windows-")))'
        echo "json=${json}" >> $GITHUB_OUTPUT
      env:
        list: ${{ steps.list.outputs.json }}
    - id: macos
      run: |
        json=$(echo ${list} | jq -c 'map(select(startswith("macos-")))'
        echo "json=${json}" >> $GITHUB_OUTPUT
      env:
        list: ${{ steps.list.outputs.json }}
