name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  runners:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      list: ${{ steps.list.outputs.all }}
    steps:
      - uses: actions/checkout@v3
      - id: list
        uses: ./

  test:
    strategy:
      fail-fast: false
      matrix:
        runner: ${{ fromJSON(needs.runners.outputs.list) }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - id: list
        uses: ./
      - run: echo "${json}"
        env:
          json: ${{ toJSON(steps.list.outputs) }}

  test-passing:
    needs: [ test ]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "All tests have passed."
